In [196]:
import numpy as np
import os
import re
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import keras
from keras.utils import to_categorical
from keras.models import Sequential,Model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers.normalization import batch_normalization
#from keras.layers.normalization import BatchNormalization
#from keras.layers.advanced_activations import LeakyReLU
from keras.layers.activation import LeakyReLU

In [197]:
dirname_train = os.path.join(os.getcwd(), 'train')
imgpath_train = dirname_train + os.sep 

images_train = []
directories_train = []
dircount_train = []
prevRoot_train=''
cant_train=0

print("leyendo imagenes de entrenamiento: ",imgpath_train)

for root, dirnames, filenames in os.walk(imgpath_train):
    for filename in filenames:
        if re.search("\.(jpg|jpeg|png|bmp|tiff)$", filename):
            cant_train=cant_train+1
            filepath = os.path.join(root, filename)
            image = plt.imread(filepath)
            images_train.append(image)
            b = "Leyendo..." + str(cant_train)
            print (b, end="\r")
            if prevRoot_train !=root:
                print(root, cant_train)
                prevRoot_train=root
                directories_train.append(root)
                dircount_train.append(cant_train)
                cant_train=0
dircount_train.append(cant_train)

dircount = dircount_train[1:]
dircount[0]=dircount[0]+1
print('Directorios leidos:',len(directories_train))
print("Imagenes en cada directorio", dircount)
print('suma Total de imagenes en subdirs:',sum(dircount))

dirname_test = os.path.join(os.getcwd(), 'test')
imgpath_test = dirname_test + os.sep 

images_test = []
directories_test = []
dircount_test = []
prevRoot_test=''
cant_test=0

print("leyendo imagenes de testeo: ",imgpath_test)

for root, dirnames, filenames in os.walk(imgpath_test):
    for filename in filenames:
        if re.search("\.(jpg|jpeg|png|bmp|tiff)$", filename):
            cant_test=cant_test+1
            filepath = os.path.join(root, filename)
            image = plt.imread(filepath)
            images_test.append(image)
            b = "Leyendo..." + str(cant_test)
            print (b, end="\r")
            if prevRoot_test !=root:
                print(root, cant_test)
                prevRoot_test=root
                directories_test.append(root)
                dircount_test.append(cant_test)
                cant_test=0
dircount_test.append(cant_test)

dircount = dircount_test[1:]
dircount[0]=dircount[0]+1
print('Directorios leidos:',len(directories_test))
print("Imagenes en cada directorio", dircount)
print('suma Total de imagenes en subdirs:',sum(dircount))

leyendo imagenes de entrenamiento:  c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\
c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\CLASS_02 1
c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\CLASS_03 62
c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\CLASS_04 213
c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\CLASS_05 105
c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\CLASS_06 949
c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\CLASS_07 37
c:\Users\vilas\Documents\TRATAMIENTO_DATOS\prueba_final_modulo\proyecto_final_modulo\train\CLASS_08 204
Directorios leidos: 7
Imagenes en cada directorio [63, 213, 105, 949, 37, 204, 62]
suma Total de imagenes en subdirs: 1633
leyendo imagenes de teste

In [198]:
labels_train=[]
indice_train=0
for cantidad in dircount_train:
    for i in range(cantidad):
        labels_train.append(indice_train)
    indice_train=indice_train+1
print("Cantidad etiquetas creadas: ",len(labels_train))

clases_carne_train=[]
indice_train=0
for directorio in directories_train:
    name = directorio.split(os.sep)
    print(indice_train , name[len(name)-1])
    clases_carne_train.append(name[len(name)-1])
    indice_train=indice_train+1

y_train = np.array(labels_train)
X_train = np.array(images_train, dtype=np.uint8) #convierto de lista a numpy

# Find the unique numbers from the train labels
classes_train = np.unique(y_train)
nClasses_train = len(classes_train)
print('Total number of outputs : ', nClasses_train)
print('Output classes : ', classes_train)

##########

labels_test=[]
indice_test=0
for cantidad in dircount_test:
    for i in range(cantidad):
        labels_test.append(indice_test)
    indice_test=indice_test+1
print("Cantidad etiquetas creadas: ",len(labels_test))

clases_carne_test=[]
indice_test=0
for directorio in directories_test:
    name = directorio.split(os.sep)
    print(indice_test , name[len(name)-1])
    clases_carne_test.append(name[len(name)-1])
    indice_test=indice_test+1

y_test = np.array(labels_test)
X_test = np.array(images_test, dtype=np.uint8) #convierto de lista a numpy

# Find the unique numbers from the train labels
classes_test = np.unique(y_test)
nClasses_test = len(classes_test)
print('Total number of outputs : ', nClasses_test)
print('Output classes : ', classes_test)

Cantidad etiquetas creadas:  1633
0 CLASS_02
1 CLASS_03
2 CLASS_04
3 CLASS_05
4 CLASS_06
5 CLASS_07
6 CLASS_08
Total number of outputs :  8
Output classes :  [0 1 2 3 4 5 6 7]
Cantidad etiquetas creadas:  810
0 CLASS_01
1 CLASS_02
2 CLASS_03
3 CLASS_04
4 CLASS_05
5 CLASS_06
6 CLASS_07
7 CLASS_08
Total number of outputs :  9
Output classes :  [0 1 2 3 4 5 6 7 8]


In [200]:
#Mezclar todo y crear los grupos de entrenamiento y testing
train_X,train_test_X,train_Y,train_test_Y = train_test_split(X_train,y_train,test_size=0.2)
#train_X=X_train
#train_X1=X_train
#test_X=X_test
#train_Y=y_train
#test_Y=y_test
print('Training data shape : ', train_X.shape, train_Y.shape)
print('Testing data shape : ',train_test_X.shape, train_test_Y.shape)
#normlizamos los valores 
train_X = train_X.astype('float32')
train_X1=train_X.astype('float32')
train_test_X = train_test_X.astype('float32')
train_X = train_X / 255.
train_X1 = train_X / 255.
train_test_X = train_test_X / 255.
 
# Change the labels from categorical to one-hot encoding
train_Y_one_hot = to_categorical(train_Y)
train_test_Y_one_hot = to_categorical(train_test_Y)
#train_Y_one_hot = to_categorical(train_Y,nClasses_train) # calses train
#train_test_Y_one_hot = to_categorical(train_test_Y,nClasses_test) # clases train -> 
 

# Display the change for category label using one-hot encoding
print('Original label 0:', train_Y[0])
print('Original label 1:', train_Y[1])
print('After conversion to one-hot 0:', train_Y_one_hot[0])
print('After conversion to one-hot 1:', train_Y_one_hot[1])
 
#train_X,valid_X,train_label,valid_label = train_test_split(train_X, train_Y_one_hot,test_size=0.001, random_state=13)
train_X,train_valid_X,train_label,train_valid_label = train_test_split(train_X, train_Y_one_hot, test_size=0.3, random_state=13)
#train_X=train_X
#valid_X=test_X
#train_label=train_Y_one_hot
#valid_label=test_Y_one_hot  #valid_label=test_Y_one_hot cambio iguala las clases al entrenamiento
 
print(train_X.shape,"\n",train_X1.shape,"\n",train_valid_X.shape,"\n",train_label.shape,"\n",train_valid_label.shape)


Training data shape :  (1306, 216, 384, 3) (1306,)
Testing data shape :  (327, 216, 384, 3) (327,)
Original label 0: 4
Original label 1: 4
After conversion to one-hot 0: [0. 0. 0. 0. 1. 0. 0. 0.]
After conversion to one-hot 1: [0. 0. 0. 0. 1. 0. 0. 0.]
(914, 216, 384, 3) 
 (1306, 216, 384, 3) 
 (392, 216, 384, 3) 
 (914, 8) 
 (392, 8)


In [201]:
INIT_LR = 1e-3
epochs = 6
batch_size = 64
 
carne_model = Sequential()
carne_model.add(Conv2D(32, kernel_size=(3, 3),activation='linear',padding='same',input_shape=(216,384,3))) ##32  384,216
carne_model.add(LeakyReLU(alpha=0.1))
carne_model.add(MaxPooling2D((2, 2),padding='same')) # tamaño de la matriz de agrupacion
#------------------------------------------
carne_model.add(Conv2D(64, kernel_size=(3, 3),activation='linear',padding='same')) ##32  384,216
carne_model.add(LeakyReLU(alpha=0.1))
carne_model.add(MaxPooling2D((2, 2),padding='same')) # tamaño de la matriz de agrupacion
carne_model.add(Conv2D(128, kernel_size=(3, 3),activation='linear',padding='same')) ##32  384,216
carne_model.add(LeakyReLU(alpha=0.1))
carne_model.add(MaxPooling2D((2, 2),padding='same')) # tamaño de la matriz de agrupacion
carne_model.add(Conv2D(256, kernel_size=(3, 3),activation='linear',padding='same')) ##32  384,216
carne_model.add(LeakyReLU(alpha=0.1))
carne_model.add(MaxPooling2D((2, 2),padding='same')) # tamaño de la matriz de agrupacion
carne_model.add(Conv2D(256, kernel_size=(3, 3),activation='linear',padding='same')) ##32  384,216
carne_model.add(LeakyReLU(alpha=0.1))
carne_model.add(MaxPooling2D((2, 2),padding='same')) # tamaño de la matriz de agrupacion
#-----------------------------------------------------

carne_model.add(Dropout(0.5))
carne_model.add(Flatten())
carne_model.add(Dense(256, activation='linear'))  #32 -> 256
carne_model.add(Dense(128, activation='linear'))  #32 -> 256
carne_model.add(Dense(64, activation='linear'))  #32 -> 256
carne_model.add(LeakyReLU(alpha=0.1))
carne_model.add(Dropout(0.5)) 
carne_model.add(Dense(nClasses_train, activation='softmax'))  #nClasses_train
 
carne_model.summary()

carne_model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adagrad(lr=INIT_LR, decay=INIT_LR / 100),metrics=['accuracy']) 
#carne_model.compile(loss=keras.losses.sparse_categorical_crossentropy, optimizer=keras.optimizers.Adagrad(lr=INIT_LR, decay=INIT_LR / 100),metrics=['accuracy'])


Model: "sequential_36"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_111 (Conv2D)         (None, 216, 384, 32)      896       
                                                                 
 leaky_re_lu_147 (LeakyReLU)  (None, 216, 384, 32)     0         
                                                                 
 max_pooling2d_111 (MaxPooli  (None, 108, 192, 32)     0         
 ng2D)                                                           
                                                                 
 conv2d_112 (Conv2D)         (None, 108, 192, 64)      18496     
                                                                 
 leaky_re_lu_148 (LeakyReLU)  (None, 108, 192, 64)     0         
                                                                 
 max_pooling2d_112 (MaxPooli  (None, 54, 96, 64)       0         
 ng2D)                                               

c:\Users\vilas\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\optimizers\legacy\adagrad.py:84: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [202]:
carne_train_dropout = carne_model.fit(train_X, train_label, batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(train_valid_X, train_valid_label))

# guardamos la red, para reutilizarla en el futuro, sin tener que volver a entrenar
carne_model.save("carnes_mnist.h5py")

Epoch 1/6
15/15 [==============================] - 97s 7s/step - loss: 2.0548 - accuracy: 0.5514 - val_loss: 2.0209 - val_accuracy: 0.6046
Epoch 2/6
15/15 [==============================] - 100s 7s/step - loss: 2.0030 - accuracy: 0.5832 - val_loss: 1.9678 - val_accuracy: 0.6046
Epoch 3/6
15/15 [==============================] - 103s 7s/step - loss: 1.9487 - accuracy: 0.5842 - val_loss: 1.9062 - val_accuracy: 0.6046
Epoch 4/6
15/15 [==============================] - 111s 7s/step - loss: 1.8910 - accuracy: 0.5821 - val_loss: 1.8303 - val_accuracy: 0.6046
Epoch 5/6
15/15 [==============================] - 114s 8s/step - loss: 1.8039 - accuracy: 0.5864 - val_loss: 1.7278 - val_accuracy: 0.6046
Epoch 6/6
15/15 [==============================] - 103s 7s/step - loss: 1.6953 - accuracy: 0.5864 - val_loss: 1.6027 - val_accuracy: 0.6046


INFO:tensorflow:Assets written to: carnes_mnist.h5py\assets


INFO:tensorflow:Assets written to: carnes_mnist.h5py\assets


In [203]:
test_eval = carne_model.evaluate(train_test_X, train_test_Y_one_hot, verbose=1)
print('Test loss:', test_eval[0])
print('Test accuracy:', test_eval[1])

11/11 [==============================] - 7s 580ms/step - loss: 1.6655 - accuracy: 0.5382
Test loss: 1.6654561758041382
Test accuracy: 0.538226306438446


In [105]:
#test_eval = carne_train_dropout.  (test_X, test_Y_one_hot)
#test_eval = carne_model.evaluate(test_X, test_Y_one_hot, verbose=1)


y_prediccion_test=carne_model.predict(test_X)#.round()

confusion_matrix(test_Y_one_hot.argmax(axis=1),y_prediccion_test.argmax(axis=1))

#y_evaluado  classes_test

#test_eval=carne_model.evaluate(test_X,test_Y_one_hot)

#print('Test loss:', test_eval[0])
#print('Test accuracy:', test_eval[1])

26/26 [==============================] - 54s 2s/step


array([[  0,   0,   0,   0,   1,   0,   0,   0,   0],
       [  0,   0,   0,   0,   1,   0,   0,   0,   0],
       [  0,   0,   0,   0,  48,   0,   0,   0,   0],
       [  0,   0,   0,   0,  97,   0,   0,   0,   0],
       [  0,   0,   0,   0,  45,   0,   0,   0,   0],
       [  0,   0,   0,   0, 459,   0,   0,   0,   0],
       [  0,   0,   0,   0,  19,   0,   0,   0,   0],
       [  0,   0,   0,   0, 114,   0,   0,   0,   0],
       [  0,   0,   0,   0,  26,   0,   0,   0,   0]], dtype=int64)

In [110]:
y_prediccion_train=carne_model.predict(train_X1)#.round()

confusion_matrix(train_Y_one_hot.argmax(axis=1),y_prediccion_train.argmax(axis=1))

52/52 [==============================] - 54s 1s/step


array([[  0,   0,   0,   0,   1,   0,   0,   0],
       [  0,   0,   0,   0,  62,   0,   0,   0],
       [  0,   0,   0,   0, 213,   0,   0,   0],
       [  0,   0,   0,   0, 105,   0,   0,   0],
       [  0,   0,   0,   0, 949,   0,   0,   0],
       [  0,   0,   0,   0,  37,   0,   0,   0],
       [  0,   0,   0,   0, 204,   0,   0,   0],
       [  0,   0,   0,   0,  62,   0,   0,   0]], dtype=int64)

In [107]:
print("y prediccion test:\n",y_prediccion_test)
print("y prediccion train:\n",y_prediccion_train)
print("Y prueba:\n",test_Y)
print("Y train one hot:\n",train_Y_one_hot)


#print("X prueba",test_X)

#print("Y entrenamiento one",train_Y_one_hot)
#print("Y test one",test_Y_one_hot)

#confusion_matrix(test_Y,y_prediccion)

y prediccion test:
 [[0.02502248 0.03621426 0.12508775 ... 0.03625148 0.12942144 0.03373645]
 [0.02503335 0.03622847 0.1250963  ... 0.03626423 0.12944363 0.03374896]
 [0.02504068 0.03623236 0.12509951 ... 0.03627035 0.12946244 0.03375624]
 ...
 [0.02503066 0.03622072 0.12510064 ... 0.0362618  0.12945348 0.03374704]
 [0.02502976 0.03622518 0.1250937  ... 0.0362615  0.12944365 0.03374545]
 [0.02504211 0.03623896 0.12510657 ... 0.03627365 0.12945141 0.03375817]]
y prediccion train:
 [[0.02505264 0.03625036 0.12511942 ... 0.03628502 0.12946868 0.03377111]
 [0.02499633 0.03618985 0.12505661 ... 0.03622678 0.12940839 0.03371052]
 [0.02504598 0.03624405 0.12510774 ... 0.036279   0.1294533  0.03376528]
 ...
 [0.02504724 0.03624348 0.12510768 ... 0.03627792 0.12945884 0.03376423]
 [0.02503075 0.03622408 0.12508531 ... 0.03626057 0.1294274  0.03374603]
 [0.02503702 0.03622614 0.12509543 ... 0.03626595 0.12943958 0.03375003]]
Y prueba:
 [0 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2